[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/about.html"
  to = "/about"
  status = 301

[[redirects]]
  from = "/services.html"
  to = "/services"
  status = 301

[[redirects]]
  from = "/contact.html"
  to = "/contact"
  status = 301
